Wed Aug  5 22:40:01 PDT 2020
Simulating day 1Simulating day 2Simulating day 3Simulating day 4Simulating day 5Simulating day 6Simulating day 7Simulating day 8Simulating day 9Simulating day 10Simulating day 11Simulating day 12Simulating day 13Simulating day 14Simulating day 15Traceback (most recent call last):
  File "/opt/ohpc/pub/compiler/intel/intelpython3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/ohpc/pub/compiler/intel/intelpython3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rchensix/covid19_air_travel_threat_modeling/main_serial.py", line 85, in <module>
    main()
  File "/home/rchensix/covid19_air_travel_threat_modeling/main_serial.py", line 82, in main
    serial_implementation(args.num_days, args.mode, args.num_procs)
  File "/home/rchensix/covid19_air_travel_threat_modeling/main_serial.py", line 67, in serial_implementation
    seir.step_metro(beta_metro_by_month[seir.mmyy])
  File "/home/rchensix/covid19_air_travel_threat_modeling/fast_model.py", line 232, in step_metro
    s1, e1, i1, r1 = self._step_seir(s0, e0, i0, r0, beta, self.t_incubation, self.t_infectious)
  File "/home/rchensix/covid19_air_travel_threat_modeling/fast_model.py", line 277, in _step_seir
    c = np.random.binomial(e, pc)
  File "mtrand.pyx", line 3100, in numpy.random.mtrand.RandomState.binomial
  File "common.pyx", line 351, in numpy.random.common.check_constraint
ValueError: n < 0
Simulating day 1Simulating day 2Simulating day 3Simulating day 4Simulating day 5Simulating day 6Simulating day 7Simulating day 8Simulating day 9Simulating day 10Simulating day 11Simulating day 12Simulating day 13Simulating day 14Simulating day 15Simulating day 16Simulating day 17Simulating day 18Simulating day 19Simulating day 20Simulating day 21Simulating day 22Simulating day 23Simulating day 24Simulating day 25Simulating day 26Simulating day 27Simulating day 28slurmstepd: error: *** JOB 56 ON compute-10-14 CANCELLED AT 2020-08-05T22:42:04 ***
